    - name: 'HaikuHelper'
      git: 'git://github.com/lupinglade/siriproxy-haikuhelper.git'
      #path: './plugins/siriproxy-haikuhelper'
      url: 'http://localhost:9399'
      controller_name: 'My Home'
      password: 'secret'


